
/**
 *  Computes some statistics about families in which the parents decide 
 *  to have children until they have at least one child of each gender.
 *  The program expects to get two command-line arguments: an int value
 * 	that determines how many families to simulate, and an int value
 *  that serves as the seed of the random numbers generated by the program.
 *  Example usage: % java OneOfEachStats 1000 1
 */

import java.util.Random;

public class OneOfEachStats {

    public static void main(String[] args) {

        int T = Integer.parseInt(args[0]);

        int seed = Integer.parseInt(args[1]);

        Random generator = new Random(seed);

        int numberOf;

        int twoChild = 0;

        int threeChild = 0;

        int fourMore = 0;

        double sum = 0;

        for (int i = 0; i < T; i++) {

            numberOf = 1;

            double x;

            double number = generator.nextDouble();

            if (number < 0.5) {

                do {

                    x = generator.nextDouble();

                    sum++;

                    numberOf++;

                } while (x < 0.5);

            } else {

                do {
					
                    x = generator.nextDouble();

                    sum++;

                    numberOf++;

                } while (x >= 0.5);
            }

            if (numberOf == 2) {

                twoChild++;

            } else if (numberOf == 3) {

                threeChild++;

            } else {

                fourMore++;
            }
        }

        sum = sum + T;

        double average = sum / T;

        int max = Math.max(twoChild, Math.max(threeChild, fourMore));

        System.out.println("Average: " + average + " children to get at least one of each gender.");
        System.out.println("Number of families with 2 children: " + twoChild);
        System.out.println("Number of families with 3 children: " + threeChild);
        System.out.println("Number of families with 4 or more children: " + fourMore);

        if (max == fourMore) {
            System.out.println("The most common number of children is 4 or more.");
        } else {
            System.out.println("The most common number of children is " + max + ".");
        }
    }
}

		    
